name: employee_list
description: Coding Assignment app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  line_icons: ^2.0.3
  calendar_date_picker2: ^0.5.2
  dart_date: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  
dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  freezed: ^2.4.1
  json_serializable: ^6.7.1

  hive_generator: ^2.0.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
